### ISSUE TITLE
function timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by Akhilll** [igniteram/protractor-cucumber-allure#27] opened 2017-10-04 07:37 UTC
[protractor-cucumber-allure.zip](https://github.com/igniteram/protractor-cucumber-allure/files/1354913/protractor-cucumber-allure.zip)
Hi, 
I am able to create POM using your framework, but the problem is when i run " NPM Test". It is just opening the web browser and directly giving the results with out interacting with the web elements.So i have added CallBack in my each step def function. Then  i am getting "function timed out after 5000 milliseconds" error message.

If i remove callBack it is running with out errors but giving results directly without interacting with application.
If i add callBack it is throwing ""function timed out after 5000 milliseconds".

Please could you help me with the solution.
``

**Comment by Vinni389** [comment] 2017-10-07 16:40
All I understood is object that you are searching for is not loaded in expected time ([default](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md) 5000 millisecs for cucumber). try [setting timeout to 10 secs](https://github.com/igniteram/protractor-cucumber-allure/blob/8be2b54833e7272a8bdc890753cac1f38ee944e4/support/hooks.js#L6) and check. If your application is Angular and in case you disabled [wait for angular](http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.waitForAngular), try to enable it when [required](https://stackoverflow.com/questions/30882671/protractor-where-to-use-browser-waitforangular).

**Comment by igniteram** [comment] 2017-10-07 16:52
@Akhilll Your particular scenario is taking more than 5 secs to load the browser, so I would do what @VaaniSai suggested, you could refer to it andlet me know if it works. Since this is more of a support question and rather not an issue with this project I am closing this issue.
Please feel free to raise a new issue !

**Closed as completed by igniteram** 2017-10-07 16:52 UTC

**Comment by Akhilll** [comment] 2017-10-07 17:15
I have tried both:
Setting timeout to10 sec, 20secs, 60 secs.
disabled wait for angular 
but no luck.

**Comment by Vinni389** [comment] 2017-10-07 17:21
So your project is not an Angular and still you are facing **timed out after 5000 milliseconds** . Did you try something like [this](https://github.com/igniteram/protractor-cucumber-typescript/blob/bcba69da81eb4dba63d2bbfee4f2aac4d8b3d084/support/hooks.ts#L10).

**Comment by Akhilll** [comment] 2017-10-07 17:23
ya tried that also....And my project is an angular application only.

**Comment by Vinni389** [comment] 2017-10-07 17:31
As you are disabling **waitForAngular** , I believe you are re-enabling it when required. It would be better if you could provide additional details (some sample code snippet which helps better understanding & reproduce the issue) in right forum (stackoverflow). Thank you
