### ISSUE TITLE
CucumberHtmlReport is not a constructor

### ISSUE THREAD

**Issue by rrawat31** [igniteram/protractor-cucumber-allure#8] opened 2017-01-31 01:23 UTC
While executing , I am getting following error : 
[17:14:37] E/launcher - CucumberHtmlReport is not a constructor
[17:14:37] E/launcher - TypeError: CucumberHtmlReport is not a constructor

**Comment by igniteram** [comment] 2017-01-31 04:49
Can you please be more specific i.e. steps you followed as it would help to narrow down the error message!

**Comment by rrawat31** [comment] 2017-01-31 05:21
I followed the instruction as per given. 
git clone "gitAddress"
npm install
npm test

==============
[17:14:33] I/launcher - Running 1 instances of WebDriver
Input file ./cucumber_report.json does not exist! Aborting
Config error
Feature: To search allure reports in google

cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
  @AllureScenario
  Scenario: Allure Reports Google
Wrong label: @AllureScenario
  ✔ Given I am on google page
  ✔ When I type "allure reports"
  ✔ Then I click search button
  ✔ Then I clear search textbox

Feature: To search cucumber in google

  @CucumberScenario
  Scenario: Cucumber Google
Wrong label: @CucumberScenario
  ✔ Given I am on google page
  ✔ When I type "cucumber"
  ✔ Then I click search button
  ✔ Then I clear search textbox

Feature: To search protractor in google

  @ProtractorScenario
  Scenario: Protractor Google
Wrong label: @ProtractorScenario
  ✔ Given I am on google page
  ✔ When I type "protractor"
  ✔ Then I click search button
  ✔ Then I clear search textbox

3 scenarios (3 passed)
12 steps (12 passed)
0m00.892s
[17:14:37] E/launcher - CucumberHtmlReport is not a constructor
[17:14:37] E/launcher - TypeError: CucumberHtmlReport is not a constructor
    at createHtmlReport (/Users/rohit/test_reporting/protractor-cucumber-allure/support/hooks.js:30:22)
    at /Users/user/test_reporting/protractor-cucumber-allure/support/hooks.js:55:17
    at /Users/user/test_reporting/protractor-cucumber-allure/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
[17:14:37] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.

**Comment by igniteram** [comment] 2017-01-31 07:45
I am assuming you are using windows environment & am able to reproduce this issue, soon would be providing a fix for it. Also a newer version cucumber-html-report module is available, I would be integrating the latest one, I think this issue exists in Windows machine only as travis couldn't pick it up, Thanks for reporting!

**Comment by igniteram** [comment] 2017-01-31 12:30
@rrawat31 This issue has been fixed and merged , please do a fresh clone of the repo and verify!

**Comment by rrawat31** [comment] 2017-01-31 17:33
@igniteram thanks for the fix. Can you share what was the issue and what was the root cause?

**Comment by mrj04** [comment] 2017-01-31 21:47
this issue is also reproducible on OSX too.

**Comment by mrj04** [comment] 2017-01-31 22:37
the latest code works for me. 

@igniteram 
How do we generate allure report and place it under reports/html ?

**Comment by igniteram** [comment] 2017-02-01 08:55
@rrawat31 glad the fix worked, the issue was with the older version of `cucumber-html-report`.
@mrj04 Allure reporter framework creates xml reports which you can be consumed in jenkins allure plugin which generates nice reports. Please follow the link in readme.md to get more understanding on this.

closing this issue now!

**Closed as completed by igniteram** 2017-02-01 08:55 UTC
Labels: bug

**Comment by rrawat31** [comment] 2017-02-03 00:11
@igniteram thanks for the fix. did you ever integrated with Jenkins? as the colorful report is not generated and instead of that black & white is generated without pie chart as well .

**Comment by edgarechm** [comment] 2017-05-17 21:25
The same issue, described by @rrawat31  appeared again in the latest version of the cucumber-html-report.

I had to patch the latest version with an older version to make the report "constructor" work again.
